apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-service
  labels:
    app: pong-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-service
  template:
    metadata:
      labels:
        app: pong-service
      annotations:
        turbine/enabled: "true"
        turbine/configmap: "turbine-sidecar-config"
    spec:
      containers:
        - name: pong-service
          image: jerrinot/turbine-demo-pong
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pong-service
  labels:
    app: pong-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: pong-service
