apiVersion: v1
kind: ServiceAccount
metadata:
  name: hook-listener

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hook-listener-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hook-listener-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hook-listener-role
subjects:
  - kind: ServiceAccount
    name: hook-listener
    namespace: default
