apiVersion: apps/v1
kind: Deployment
metadata:
  name: hook-listener-service
  labels:
    app: hook-listener-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hook-listener-service
  template:
    metadata:
      labels:
        app: hook-listener-service
    spec:
      serviceAccountName: hook-listener
      containers:
        - name: hook-listener
          image: jerrinot/turbine-demo-hook-listener
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hook-listener-service
  labels:
    app: hook-listener-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: hook-listener-service
