# This is a basic workflow to help you get started with Actions

name: RUN CI
on:
  push:
    paths-ignore:
      - '**.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          go-version: [1.16.x]

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
          
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch require Go modules and build
        working-directory: ./hook-listener
        run: |
          go mod download \
          go build -v .

      - name: Build hook listener
        id: docker_build_hook_listener
        uses: docker/build-push-action@v2
        with:
          context: ./hook-listener
          file: ./hook-listener/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          load: true
          tags: jerrinot/turbine-demo-hook-listener:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: functional test
        id: functional-test
        run: go test -v ./...